{
    "name": "POS Daily Sales Report | POS Report Advance | POS Category wise Sales Report, POS Product wise Sales Report , POS Product Stock Report, POS Payment Collection Report.",
    'version': '14.1.1.1',
    "summary": """ 
    POS Daily Sales Report | POS Report Advance | POS Category wise Sales Report, POS Product wise Sales Report , POS Product Stock Report, POS Payment Collection Report.
    """,    
    'description':"POS Daily Sales Report | POS Report Advance | POS Category wise Sales Report, POS Product wise Sales Report , POS Product Stock Report, POS Payment Collection Report.",
    "price": 24,
    'currency': 'EUR',
    "author" : "MAISOLUTIONSLLC",
    'sequence': 1,
    "email": 'apps@maisolutionsllc.com',
    "website":'http://maisolutionsllc.com/',
    'license': 'OPL-1',
    'category':"Point of Sale",
    "depends": [
        "point_of_sale",
    ],
    "data": [
        'security/ir.model.access.csv',
        'wizard/res_company_view.xml',
        'wizard/pos_order_category_report.xml',
        'report/pos_report_category_template.xml',
        'wizard/pos_order_product_report.xml',
        'report/pos_report_product_template.xml',
        'wizard/pos_order_product_stock_report.xml',
        'report/pos_report_product_stock_template.xml',
        'wizard/pos_order_payment_report.xml',
        'report/pos_order_payment_template.xml',
        'report/pos_order.xml',
    ],
    'qweb': [],
    'css': [],
    'js': [],
    'images': ['static/description/main_screenshot.png'],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
