{
    'name': 'Stock Valuation By Vendor Mv',
    'version': '14.0.1.0.0',
    'summary': 'Materialized View Report',
    'author': 'Generated by ChatGPT',
    'depends': ['stock'],
    'data': ['views/stock_valuation_by_vendor_mv_views.xml'],
    'installable': True,
    'auto_install': False,
}