{
    'name': 'All in One Dashboard Lite',
    'version': '14.0.1.0.0',
    'category': 'Productivity',
    'summery': 'Smart Dashboard',
    'author': 'INKERP',
    'website': "https://www.INKERP.com",
    'depends': ['web'],
    'data': [
        'security/custom_dashboard_security.xml',
        'security/ir.model.access.csv',
        'views/eg_custom_dashboard_item_view.xml',
        'views/dashboard_template_view.xml',
        'views/custom_dashboard_board.xml',
        'data/custom_dashboard_client_actions.xml',
    ],
    'qweb': [
        'static/src/xml/ColorPickerWidget.xml',
        'static/src/xml/DashboardIconPicker.xml',
        'static/src/xml/DashboardTilePreview.xml',
        'static/src/xml/DashboardTile.xml',
        'static/src/xml/custom_dashboard_qweb.xml',
        'static/src/xml/custom_dashboard_view.xml',
        'static/src/xml/CustomDashboardBoard.xml',
    ],
    'demo': [
        'demo/dashboard_charts_demo.xml',
    ],
    'images': ['static/description/banner.gif'],
    'license': "OPL-1",
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_hook',
    'uninstall_hook': "uninstall_hook",
}
